# Generated by Django 3.2.2 on 2022-02-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='emailaddress',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
