# Generated by Django 3.1.6 on 2021-03-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=300)),
                ('Brand', models.CharField(max_length=300)),
                ('Cost', models.CharField(max_length=300)),
                ('Size', models.CharField(max_length=300)),
                ('Mouth_size', models.CharField(max_length=300)),
                ('Color', models.CharField(max_length=300)),
                ('Supplied_by', models.CharField(max_length=300)),
                ('Current_quantity', models.CharField(max_length=300)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier')),
            ],
        ),
    ]
