# Generated by Django 3.1.6 on 2021-03-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterbottle',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='Cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='Current_quantity',
            new_name='current_quantity',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='Mouth_size',
            new_name='mouth_size',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='Size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='waterbottle',
            old_name='supplier',
            new_name='supplied_by',
        ),
        migrations.RemoveField(
            model_name='waterbottle',
            name='Supplied_by',
        ),
    ]
