# Generated by Django 3.1.6 on 2021-03-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0002_auto_20210305_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
