# Generated by Django 3.1.6 on 2021-03-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0003_auto_20210310_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='time',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
