# Generated by Django 3.1.6 on 2021-03-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0005_auto_20210310_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySupplier',
        ),
    ]
