# Generated by Django 3.1.6 on 2021-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0006_delete_mysupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='cost',
            field=models.IntegerField(max_length=300),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='current_quantity',
            field=models.IntegerField(max_length=300),
        ),
    ]
