# Generated by Django 3.1.6 on 2021-03-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0007_auto_20210310_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='current_quantity',
            field=models.IntegerField(),
        ),
    ]
