# Generated by Django 3.1.6 on 2021-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0008_auto_20210310_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
