# Generated by Django 3.1.6 on 2021-05-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0009_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterbottle',
            old_name='supplied_by',
            new_name='supplier',
        ),
    ]
